# Introducción

Desde hace más de medio siglo los distintos regímenes democrático alrededor del mundo han sufrido una baja sostenida en la confianza que los ciudadanos depositan en sus instituciones políticas [@valgardssonCrisisPoliticalTrust2025]. Preocupados por la supervivencia de este régimen político, los estudiosos de la democracia han destacado durante todo este tiempo la importancia que este tipo de confianza tiene para su estabilidad y buen funcionamiento [@zmerliPoliticalTrust2022]. Desde el punto de vista de las instituciones, se argumenta que cuando son percibidas como confiables, ostentan una mayor efectividad en la implementación de servicios públicos, facilitan el consenso de los perdedores electorales, reducen la evasión fiscal y poseen una mayor resistencia a periodos de crisis económicas y sociales [@vandermeerDeeplyRootedConcern2017; @newtonSocialPoliticalTrust2017; @citrinPoliticalTrustCynical2018]. A su vez, se plantea que los ciudadanos que confían en sus instituciones tendrían una mayor tendencia a obedecer la ley, a interesarse en política y a respaldar políticas públicas que impliquen un riesgo o sacrificio personal [@citrinPoliticalTrustCynical2018; @zmerliPoliticalTrust2022]. Por el contrario, se asume comúnmente que los ciudadanos que no confían en sus instituciones políticas serían más propensos a radicalizarse y a impulsar cambios que podrían significar a largo plazo un peligro para la supervivencia de la democracia [@andersonSensitiveLeftImpervious2008]. En este sentido, la confianza política se concibe como una condición previa para la consolidación de un régimen democrático sostenible en el tiempo [@vandermeerDeeplyRootedConcern2017].

En función de estas consideraciones sobre la importancia de este fenómeno para la democracia se argumenta que, a fin de revertir esta crisis de confianza es necesario primero entender en profundidad los diversos factores que influyen en la forma en que los ciudadanos construyen la confianza política [^1]. A grandes rasgos, la literatura indica que habrían dos grupos de perspectivas para explicar sus orígenes y variaciones [@mishlerWhatAreOrigins2001; @vandermeerDeeplyRootedConcern2017; @zmerliPoliticalTrust2022]. Por un lado, se encuentra la perspectiva institucional o "desde arriba" la cual pone énfasis en los procesos endógenos a la institucionalidad. Según esta orientación, la confianza en las instituciones políticas tendría su origen en una evaluación racional de su desempeño en cumplir con las expectativas de los ciudadanos en distintos ámbitos, la cual estaría sujeta a cambiar producto de la contingencia [@citrinPoliticalTrustCynical2018; @hardinWeWantTrust1999; @vandermeerEconomicPerformancePolitical2018]. En particular, se tiende a aludir a tres fenómenos que han demostrado ser constitutivos de la percepción del desempeño institucional, como lo son la situación económica nacional, la corrupción y la justicia distributiva. Por otro lado, se observa una perspectiva sociocultural o "desde abajo" ligada al concepto de capital social, la cual se centra en factores exógenos a las instituciones cómo lo son el conjunto de orientaciones valóricas y disposiciones a confiar, cooperar y solidarizar con los otros que los individuos adquieren en los procesos de socialización primaria durante las etapas tempranas de la vida. Según esta perspectiva, la presencia de estos valores llevaría a los individuos a involucrarse con los otros y a cooperar en función de objetivos comunes, lo cual se traduciría en una tendencia a confiar en las instituciones políticas [@putnamMakingDemocracyWork1993]. En especifico, se pone énfasis en la importancia de la confianza generalizada como la piedra angular de este grupo de factores, en cuanto está a la base del resto de disposiciones [@uslanerDemocracySocialCapital1999; @zmerliSocialTrustAttitudes2008]. 

Al evaluar la pertinencia de ambas perspectivas desde el punto de vista empírico, gran parte de las investigaciones previas han llevado a la misma conclusión: tanto la percepción del desempeño en estas áreas como la confianza generalizada se asocian con la confianza política, aunque el efecto de la primera tiende a ser más intenso que el de la segunda. No obstante, estas investigaciones presentan, al menos, dos limitaciones importantes que resulta necesario superar para obtener una comprensión más profunda  de este fenómeno. En primer lugar, gran parte de estos estudios conciben la relación entre confianza generalizada y confianza política como un vínculo *exclusivamente* directo. Lo anterior ignora que la confianza generalizada es un lente a través del cual los individuos interpretan el mundo y que, por tanto, el verdadero potencial de este fenómeno es el de moderar la relación entre percepción del desempeño y confianza política [@oskarssonGeneralizedTrustPolitical2010]. En contraste, se propone la necesidad de complementar este análisis con uno que indague en la posibilidad de que la confianza generalizada modere la relación entre la percepción del desempeño institucional y la confianza política. Lo anterior sobre la base de que la confianza generalizada se origina en una disposición moral que se mantiene en el tiempo y que orienta la interpretación que los ciudadanos llevan a cabo de los fenómenos que los rodean, y que se traduciría en que aquellos que confían en los demás serían menos susceptibles a disminuir su confianza en las instituciones políticas en función de malos desempeños [@oskarssonGeneralizedTrustPolitical2010; @uslanerMoralFoundationsTrust2002]. En segundo lugar, gran parte de los estudios que han comparado detenidamente ambas perspectivas se han realizado en países con altos niveles comparativos de confianza en los otros. En contraste, en esta investigación se plantea la posibilidad de que estos resultados varíen en democracias que funcionan al alero de sociedades con bajos niveles de confianza generalizada [@bargstedSocialPoliticalTrust2023]. 

Para avanzar estas limitaciones, el caso chileno presenta un terreno particularmente fértil. Lo anterior debido a que, en contraste con lo que la perspectiva institucional invitaría a pensar, el país ha presenciado por bastante tiempo la paradoja entre la persistencia de un desempeño institucional positivo y la profundización de un extendido descontento frente a las instituciones políticas [@huneeusDemocraciaSemisoberanaChile2014; @pnudChile20Anos2017]. Así, por un lado, desde el retorno a la democracia el Estado ha sabido mejorar la condiciones materiales de los chilenos en diversos aspectos, a la vez que ha reducido la desigualdad de ingresos y ha mantenido niveles comparativamente bajos de corrupción política [@coppedgeVDemDatasetV152025; @pnudInformeSobreDesarrollo2024; @worldbankPovertyInequalityPlatform2025]. Por el otro lado, todas las instituciones políticas han presenciado una disminución sustantiva de los niveles de confianza que les otorga la ciudadanía en los últimos 30 años [@bargstedCulturaPoliticaDiagnostico2018; @corporacionlatinobarometroLatinobarometroSeriesTiempo1995]. La diferencias exhibidas entre desempeño y confianza política invitan a pensar que en esta crisis de legitimidad pueden estar influyendo factores exógenos a la institucionalidad política. En particular, se afirma la importancia que podrían tener los bajos niveles de confianza generalizada en cuanto reflejo de un proceso de erosión del lazo social chileno [@araujoDesmesurasDesencantosIrritaciones2019; @araujoCircuitoDesapegoNeoliberalismo2025a]. 

Aunque la pregunta por la confianza política ya ha sido abordada por otros investigadores con anterioridad [véase @bargstedSocialPoliticalTrust2023; @moralesquirogaEvaluandoConfianzaInstitucional2008; @riffoQueInfluyeConfianza2019; @saldanazunigaConfianzaInstitucionesPoliticas2019; @segoviaMalaiseDemocracyChile2016; @segoviaConfianzaInstitucionesPoliticas2008], se argumenta que estos estudios dejan algunos vacíos que buscarán ser llenados por la presente investigación.  En primer lugar, se observa una brecha temporal, en cuanto la mayoría de los estudios mencionados (a excepción de Bargsted et al. [-@bargstedSocialPoliticalTrust2023]) se construyen sobre datos levantados con anterioridad al 2019. A lo largo de este periodo de tiempo que va desde el 2019 a la fecha, han ocurrido un conjunto de hitos como el estallido social, la pandemia de covid-19 y el fracaso de los procesos constituyentes. Debido a la relevancia de estos fenómenos en la configuración del panorama sociopolítico nacional, es importante explorar la posibilidad de variaciones en la magnitud de las relaciones encontradas con anterioridad. En segundo lugar, se identifica un déficit local en el estudio de algunos posibles determinantes de la confianza política que podrían ser particularmente importantes para el caso chileno, como la percepción de justicia distributiva, la corrupción y la confianza interpersonal. Por último, se reconoce que ninguno de estos estudios lleva a cabo una comparación directa entre, por un lado, los factores asociados al desempeño institucional y, por el otro, la confianza generalizada.

Al alero de esta problematización, el presente estudio buscará analizar el impacto que tanto la percepción del desempeño institucional como la confianza generalizada tienen sobre la confianza política. A su vez, se pretende explorar posibles variaciones en la relación entre la percepción del desempeño institucional y la confianza política según el nivel de confianza generalizada presente en cada uno de los individuos. Para esto, se aplicará un modelo de regresión lineal con Mínimos Cuadrados Ordinarios (MCO) sobre datos extraídos de la Encuesta Latinobarómetro en su versión del 2024 (*n* = 1200). De esta forma, se buscará estimar la intensidad y significancia estadística de cada una de las relaciones planteadas, a modo de contrastar las hipótesis que guiarán esta investigación. 

A continuación se presentará un apartado con la pregunta de investigación y los objetivos que guiarán esta investigación. Luego, se discutirán los conceptos principales y las hipótesis que se buscarán contrastar. Por último, se detallará la metodología a utilizar.

## Pregunta de investigación

¿Cómo influyen la percepción del desempeño institucional y la confianza generalizada en la confianza política de los ciudadanos chilenos?

## Objetivo general

Analizar la influencia que la percepción del desempeño institucional y la confianza generalizada tienen en la confianza política de los ciudadanos chilenos. 

## Objetivos específicos 

1. Analizar el rol de la percepción del desempeño institucional en la confianza política de los ciudadanos chilenos.
2. Examinar el rol de la confianza generalizada en la confianza política de los ciudadanos chilenos.
3. Explorar si varía o no la relación entre la percepción del desempeño institucional y la confianza política al moderar por el nivel de confianza generalizada de los ciudadanos chilenos.

[^1]: El concepto central de esta investigación es el de confianza política. Como se verá en la introducción, este se entiende como un tipo particular de confianza dirigido hacia las instituciones del régimen político. En función de lo anterior, y siguiendo las prácticas comunes en la literatura internacional sobre el tema, se utilizará este concepto como un equivalente al de "confianza en las instituciones políticas".



