# Metodología

## Datos

En específico, se trabajó sobre datos secundarios a partir de indicadores que serán extraídos de la encuesta Latinobarómetro, en su ola correspondiente al año 2023. Para el caso chileno, esta encuesta presenta una muestra de 1200 entrevistados, los cuales fueron seleccionados mediante una muestreo probabilístico en tres etapas y representan al 100% de la población adulta en el país. Estos datos fueron levantados entre el 20 de febrero y el 1 de abril del 2023 mediante entrevistas presenciales en formato cara a cara.

## Variables

### Variable dependiente

Para medir el nivel de confianza política, se usó la  siguiente pregunta: Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿Cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna (4) confianza en...?. La elección de esta pregunta constituye una ventaja metodológica, debido a que no hace ninguna referencia al desempeño de las instituciones ni a quienes las ocupan, lo que nos permite asegurarnos que se están tomando como referencia las instituciones políticas en cuanto objeto político distinguible de los actores que las lideran. De la lista de instituciones que se le menciona a los encuestados, se analiza el nivel de confianza reportado en las instituciones centrales del régimen político democrático, es decir, el Congreso, el gobierno, el Poder Judicial y los partidos políticos. A partir de las respuestas de cada una de estas instituciones se construyó un índice aditivo de escala 1-10 ($\alpha$ = 0.78) que sirve de variable para medir la confianza política como una dimensión única. Lo anterior se justifica a partir del reconocimiento por gran parte de la literatura de que, a nivel empírico, las actitudes expresadas frente a este conjunto de instituciones están determinadas la orientación general que los individuos tienen hacia el sistema político [@marienMeasuringPoliticalTrust2013; @zmerliPoliticalTrust2022]. A su vez, se ha comprobado la pertinencia de este indicador en investigaciones previas [@bargstedSocialPoliticalTrust2023; @zmerliIncomeInequalityDistributive2015].



### Variables independientes

Para estudiar la pertinencia de las explicaciones sobre las causas de la confianza política mencionadas en el apartado de marco teórico, se seleccionó un indicador para cada una. En lo que respecta a la percepción de la situación económica del país, se construyó un índice sumativo de escala 1-10 ($\alpha$ = 0.76) a partir de las respuestas a tres preguntas: 1) ¿Cómo calificaría en general la situación económica actual del país?; 2) ¿Considera Ud. que la situación económica actual del país está mucho mejor, un poco mejor, igual, un poco peor, o mucho peor que hace doce meses?; 3) ¿Y en los próximos doce meses cree Ud. que, en general, la situación económica del país será mucho mejor, un poco mejor, igual, un poco peor, o mucho peor que ahora? La primera de estas comprende los valores desde el 1 (Muy buena) hasta el 5 (Muy mala). Por otro lado, la segunda y la tercera incluyen el mismo rango de valores pero cambia el fraseo, el cual va desde Mucho mejor (1) a Mucho peor (5). A partir de este indicador, se obtiene un panorama más completo de la percepción del individuo a este respecto, debido a que no se limita a conocer únicamente su opinión sobre el presente económico nacional sino que también la comparación que hace con el pasado y sus proyecciones a futuro [@saldanazunigaConfianzaInstitucionesPoliticas2019]. 

En cuanto a la percepción de la corrupción, se hizo uso de la pregunta ¿Cuánto cree Ud. que se ha progresado en reducir la corrupción en las instituciones del Estado en estos últimos 2 años?, la cual incluye como categorías de respuesta valores del 1 (Mucho) al 4 (Nada). De esta forma, se podrá obtener información de la evaluación que los ciudadanos llevan a cabo sobre la eficiencia de las instituciones en combatir la corrupción. A su vez, este indicador ha sido utilizado con éxito en investigaciones similares [@andrianiInstitutionalTrustCorruption2021]. Por otro lado, en lo que respecta a la percepción de la desigualdad de ingresos se ocupó la pregunta ¿Cuán justa cree Ud. que es la distribución del ingreso en Chile?, la cual comprende valores del 1 (Justa) al 4 (Muy injusta). Este indicador se condice con los estudios sobre percepción de desigualdad y confianza política [@leeEconomicPerformanceIncome2020; @wuIncomeInequalityDistributive2019; @zmerliIncomeInequalityDistributive2015]. Para efectos del análisis, ambos indicadores fueron transformados en variables *dummy*. En el caso del primero se agruparon, por un lado, las categorías "Mucho" y "Algo" y, por el otro lado, las de "Poco" y "Nada". A su vez, en lo que respecta al segundo se agruparon en una categoría las respuestas "Muy Justa" y "Justa" y en otra las de "Injusta" Y "Muy injusta". En ambas recodificaciones se ordenaron las categorías de respuesta de manera tal que el valor "1" indique una percepción negativa del desempeño institucional en cada uno de estos ámbitos.
	
Por último, para medir la confianza generalizada se utilizó la siguiente pregunta: Hablando en general, ¿Diría Ud. que se puede confiar en la mayoría de las personas o que uno nunca es lo suficientemente cuidadoso en el trato con los demás? Esta, a su vez, ofrece las siguientes dos categorías de respuesta: 1) Se puede confiar en la mayoría de las personas; 2) No se puede confiar en la mayoría de las personas. Al igual que las últimas dos, esta variable se recodificó para que adoptara valores "1" y "0", en los que la puntuación "1" expresa confianza generalizada y la puntuación "0" indica falta de este atributo. Este indicador, difundido originalmente por Rosenberg [-@rosenbergMisanthropyPoliticalIdeology1956], es el más utilizado por las encuestas para medir la confianza generalizada, y por tanto es adoptado por la mayoría de las investigaciones que ocupan este concepto [@andrianiInstitutionalTrustCorruption2021; @garcia-sanchezEconomicInequalityUnfairness2025a; @mattesSocialPoliticalTrust2018; @newtonThreeFormsTrust2011; @oskarssonGeneralizedTrustPolitical2010]. Aunque algunos investigadores ponen en duda su funcionalidad debido a que el significado de la frase “la mayoría de las personas” se puede prestar para interpretaciones distintas según el individuo [@justwanMeasuringSocialTrust2018], se afirma su pertinencia en cuanto la amplitud en su fraseo permite asumir que lo que se está midiendo es la confianza en los desconocidos [@oskarssonGeneralizedTrustPolitical2010; @uslanerMoralFoundationsTrust2002], lo que se encuentra en concordancia con la definición de confianza generalizada adoptada en este estudio.
	
### Variables de control

  Además de los indicadores ya mencionados, se incluyeron en el análisis un conjunto de variables sociodemográficas a modo de variables de control. Estas son: sexo, edad, nivel educacional, estatus social subjetivo y afiliación religiosa.

## Métodos

Una vez procesada la información contenida en la encuesta Latinobarómetro, se llevaron a cabo las mediciones pertinentes a los objetivos de la investigación. Para esto, en primer lugar, se calcularon una serie de estadísticos descriptivos sobre las variable dependiente e independientes con el objetivo de presentar un panorama general sobre el estado de estas en la población chilena. En segundo lugar, en orden de comprobar las hipótesis esgrimidas en el apartado anterior, se construyeron modelos de regresión múltiple (MCO). Se eligió esta técnica de investigación en cuanto permite estimar la intensidad y la significación estadística de las relaciones formuladas, así como controlar por el efecto de otras variables, reduciendo al máximo posible el error de en la estimación.  Con los datos que proporcionan los modelos, es posible llevar a cabo inferencias respecto a la influencia del desempeño institucional y de la confianza generalizada en la confianza política, así como explorar de qué forma interactuan estos dos posibles determinantes.