# Discusión

El primer hallazgo que se presenta en esta investigación tiene que ver con la importancia relativa que cada uno de los factores asociados a la percepción del desempeño institucional tiene en la construcción de confianza política en Chile. En concordancia con lo planteado en los antecedentes (*H1*, *H2* y *H3*), es posible afirmar que la evaluación del desempeño que las instituciones tienen en distintas áreas prioritarias para la ciudadanía efectivamente tiene relación con los juicios de confianza hacia estas. En particular, se evidencia que la percepción de la situación económica nacional, la evaluación del desempeño en reducir la corrupción y la percepción de justicia distributiva se relacionan positivamente con la confianza que los ciudadanos chilenos depositan sobre sus instituciones políticas. Sin embargo, en los resultados presentados se encuentra la particularidad de que estas últimas dos aparecen en mayor grado relacionadas con el fenómeno de estudio que la primera. Si se compara la magnitud del efecto que la percepción de la economía y de la corrupción exhiben en otras investigaciones, se encuentra que la evidencia aquí presentada difiere de lo presenciado para Europa [@oskarssonGeneralizedTrustPolitical2010; @torcalDeclinePoliticalTrust2014a; @torcalPoliticalTrustWestern2017] y para Chile [@riffoQueInfluyeConfianza2019; @saldanazunigaConfianzaInstitucionesPoliticas2019; @segoviaMalaiseDemocracyChile2016], aunque coincide con investigaciones que se enfocan en otros países de América Latina [@mainwaringStateDeficienciesParty2006; @stoyanTrustGovernmentInstitutions2016] y en la región en su conjunto [@bargstedPoliticalTrustLatin2017; @mattesSocialPoliticalTrust2018]. A su vez, esta distancia entre lo encontrado en este estudio y lo presenciado en la literatura internacional se mantiene si se comparan las magnitudes de la percepción de la economía y de la justicia distributiva, al menos en lo que respecta a América Latina [@zmerliIncomeInequalityDistributive2015]. Antes de asumir que esto sería la consecuencia de que los chilenos le restan importancia a la economía en sus juicios de confianza política (lo cual por la intensidad de su efecto pareciera no ser cierto), resulta más pertinente poner atención en las posibles razones detrás de la relevancia política que tanto la corrupción como la desigualdad han adquirido en el último tiempo. 

La importancia que los chilenos le otorgan a la corrupción en sus actitudes políticas se puede explicar a partir de la importancia que este tema ha adquirido en el debate público de los últimos años. Desde este punto de vista, se evidencia que la preocupación por la corrupción política en Chile ha adquirido especial fuerza desde la década pasada debido a una serie de escándalos que han puesto en entredicho la percepción generalizada de que las situaciones de mal uso de fondos públicos en el país comprendían casos aislados de individuos inescrupulosos que se desviaban de la práctica recurrente instalada en el sistema político nacional [@lunaDemocraciaMuertaChile2024]. Durante este periodo se presenció el destape de prácticas como el financiamiento irregular por parte de empresas privadas a las campañas políticas de todo el espectro ideológico a cambio de legislación favorable (caso SQM, caso PENTA), el cohecho y el tráfico de influencia para obtener información privilegiada en juicios (caso Audios), o la suscripción de millonarios contratos entre instituciones públicas y fundaciones ligadas a partidos de gobierno (caso Convenios). La frecuencia con la que se han conocido estos eventos, la transversalidad con la que han afectado a los distintos poderes del Estado y su persistencia en el tiempo han tenido como consecuencia que los chilenos dejen de ver la corrupción como un hecho aislado y la empiecen a percibir como una práctica recurrente y arraigada en las instituciones políticas del país [@castiglioniChallengesPoliticalRepresentation2016; @lunaDelegativeDemocracyRevisited2016a]. En este sentido, la apreciación de que el sistema político y las élites están coludidas en la persecución de intereses individuales a costas del bien público ha tenido como correlato el fortalecimiento de una sensación de que las instituciones políticas son abusivas, minando así la confianza en estas [@araujoCircuitoDesapegoNeoliberalismo2025a; @lunaDelegativeDemocracyRevisited2016a].

En cuanto a la relevancia que se le concibe a la justicia distributiva, cabe mencionar como posible explicación el proceso de politización de las desigualdades que el país ha presenciado durante este siglo. Durante el periodo de la Concertación de Partidos por la Democracia los distintos gobiernos tomaron la decisión de mantener alejado del debate público las cuestiones redistributivas, ya sea mediante su reducción a criterios técnicos que ignoraban su carácter conflictivo, así como mediante la desmovilización social producto del quiebre en las relaciones entre estos partidos y los actores de la sociedad civil que históricamente habían levantado estas consignas, a saber, los movimientos sindicales y de pobladores [@barozetEntreUrnaRedes2016; @huneeusDemocraciaSemisoberanaChile2014; @robertsRePoliticizingInequalitiesMovements2016]. No obstante lo anterior, la experiencia cotidiana de los altos niveles de desigualdad socioeconómica, expresada no solo en la forma de diferencias en el patrimonio sino que también en el trato desigual que reciben las personas en función de jerarquías sociales (de clase, raza y género) y en las dificultades para ejecutar la promesa de movilidad social vía mercado, terminó desembocando en la repolitización de las demandas redistributivas de la mano de movimientos sociales. De esta forma, van a surgir a lo largo de la década distintos ciclos de movilizaciones que van a poner en el centro de la opinión pública demandas por una sociedad más igualitaria, a través de exigencias por cuestiones como una mayor redistribución de la riqueza, el acceso universal a servicios básicos como salud y educación, y una mayor horizontalidad en las interacciones cotidianas. En este contexto, se ha alimentado en gran parte de la ciudadanía chilena un repertorio de actitudes negativas hacia las instituciones políticas, las cuales son vistas como responsables principales de la mantención de un sistema en donde las expectativas de movilidad social y bienestar económico se estrellan constantemente con su naturaleza exclusionaria [@castiglioniChallengesPoliticalRepresentation2016; @robertsRePoliticizingInequalitiesMovements2016; @sommaNoWaterOasis2021a].  

El segundo hallazgo a discutir hace referencia a la fuerte relación positiva que se encontró entre la confianza generalizada y la confianza política para el caso chileno (*H4*). Este descubrimiento resulta por si solo novedoso, en cuanto se distancia de las investigaciones previas que habían demostrado consistentemente que, al controlar por por el desempeño institucional en diversas áreas, la confianza generalizada quedaba remitida a una variable de segundo orden en lo que respecta a la construcción de juicios de confianza en las instituciones [@dellmuthWhyNationalInternational2020; @granadosRaceInequalityPolitical2025; @mainwaringStateDeficienciesParty2006; @morrisCorruptionTrustTheoretical2010; @newtonSocialPoliticalTrust2017; @rahnTalePoliticalTrust2005; @torcalDeclinePoliticalTrust2014a]. No obstante lo anterior, aun más novedosa resulta la evidencia del efecto de moderación que tendría la confianza generalizada en la relación que la percepción de la situación económica y la percepción de la justicia distributiva presentan con la confianza política (*H5* y *H7*). Estos resultados profundizan en lo encontrado por Oskarsson [-@oskarssonGeneralizedTrustPolitical2010] para el caso europeo, sin embargo, con una diferencia sustancial. Mientras que en el estudio citado la confianza generalizada disminuye el tamaño del efecto que tendrían las variables de percepción del desempeño institucional en la confianza política, en los resultados presentados en esta investigación esta moderación adopta el sentido contrario. Lo anterior quiere decir que en vez de disminuir la magnitud de la relación, la confianza generalizada en los ciudadanos chilenos la potencia. 

Estos resultados con respecto a la confianza generalizada obligan a cuestionar hasta cierto punto los argumentos sobre los cuales se concibió esta relación. Por un lado, estos presentan evidencia para corroborar el planteamiento de que la perspectiva optimista que estaría a la base de la disposición a confiar en los otros más allá del círculo cercano funcionaría como un lente a través del cual los individuos interpretan el mundo que los rodea, incluido las instituciones políticas. Lo anterior se ve reflejado no solo en la relación directa entre la confianza generalizada y la confianza política, sino que también en la capacidad de la primera para moderar la relación entre la percepción del desempeño y la confianza en instituciones. Por otro lado, se evidencia que los individuos que confían en los demás le atribuyen una mayor importancia a la situación económica nacional y a la justicia distributiva al momento de construir sus juicios de confianza en las instituciones. Así, no se presenta lo que fue hipotetizado en un principio, a saber, que los individuos que manifiestan confianza generalizada, al ser menos dependientes de la información para entablar relaciones de confianza, serían menos propensos a disminuir su confianza política en función de una mala gestión institucional. Por el contrario, pareciera ser que esta información, al menos en lo que a la economía y a la desigualdad respecta, refuerza el vinculo entre ambos tipos de confianza. 

Lo anterior se podría explicar por el significado que los individuos le atribuyen a este tipo de información. El mismo Uslaner [@uslanerMoralFoundationsTrust2002] argumenta que la confianza en los demás tiene por fundamento un ideal igualitario, según el cual se trata a todos por igual y se coopera con el resto para asegurar que mejoren las condiciones de vida de los menos favorecidos, en cuanto todos son parte de una misma comunidad moral. En este sentido, se argumenta la posibilidad de que los individuos interpreten un buen desempeño en estos dos ámbitos como un avance hacia la consecución de este ideal, llevándolos a percibir en mayor medida a las instituciones como poseedoras de sus mismos valores y por tanto confiando más en ellas. Por el contrario, esta afirmación tendría como contraparte la posibilidad de que aquellos individuos que confían en los demás no se mantengan como una base social estable de las instituciones en momentos de crisis socioeconómica. A su vez, no queda claro por qué este disposición a confiar no modera también la relación entre corrupción y confianza política (*H6*), especialmente si se tiene en cuenta que los hechos de corrupción están igualmente asociados a la erosión de los ideales de igualdad [@uslanerMoralFoundationsTrust2002]. Debido a lo anterior, para comprender en profundidad la naturaleza moderadora de la confianza generalizada es necesario complementar este estudio con la investigación en contextos distintos al chileno. 

El tercer hallazgo de este estudio guarda relación con el argumento según el cual la paradoja entre, por un lado, el desempeño positivo de la institucionalidad chilena y, por el otro, las manifestaciones de rechazo de la ciudadanía hacia estas, tenía como consecuencia la necesidad de buscar los factores detrás de la construcción de la confianza política en los chilenos afuera del ámbito propiamente institucional (*H8*). Los resultados evidenciados complejizan esta afirmación. En particular, los resultados dan cuenta de que esta diferencia entre desempeño y actitudes no significa que los chilenos no presten atención a la capacidad de las instituciones para mejorar sus condiciones de vida a la hora de evaluarlas como confiables o no. Sino que, cómo han señalado otros estudios, pareciera haber una distancia entre lo que sugieren los indicadores macroeconómicos y su experiencia cotidiana [@pnudChile20Anos2017; @robertsRePoliticizingInequalitiesMovements2016]. Así, la estabilidad de los equilibrios macroeconómicos, la mantención de una corrupción política baja en términos comparativos, y la reducción de la desigualdad de ingresos no se condicen con la experiencia de los individuos de una desigualdad multidimensional y estructural que permea todos los ámbitos de la vida social, y que se concibe como perpetuada por una institucionalidad corrupta que aprovecha su poder para reproducir los privilegios de las élites que la ocupan en desmedro de los intereses de la mayoría [@araujoDesmesurasDesencantosIrritaciones2019; @araujoCircuitoDesapegoNeoliberalismo2025a]. En este sentido, se argumenta que es esta experiencia la que se ocupa como criterio para evaluar el desempeño de las instituciones, y no la alusión a indicadores abstractos. 

No obstante lo anterior, queda claro a partir de la evidencia encontrada que no basta con hacer alusión a estos factores, sino que es necesario ir más allá y considerar la importancia que el vínculo social tiene en los juicios de confianza política de los chilenos. Así, la constatación de la importancia que la confianza generalizada demostró tener en los modelos presentados, incluso por sobre la percepción de la situación económica y de la corrupción, sirve como evidencia para corroborar el planteamiento de que subyacente a la baja confianza de las instituciones se encontraría un largo proceso de erosión del tejido social chileno. Cómo se mencionó en los antecedentes, este proceso estaría caracterizado por el desapego respecto a las normas e instituciones que rigen la sociedad [@araujoDesmesurasDesencantosIrritaciones2019; @araujoCircuitoDesapegoNeoliberalismo2025a]. Lo anterior no implica la completa desafiliación de la sociedad, sino que se traduce en una especie de retraimiento que se caracteriza por la preocupación y confianza en los círculos familiares -entendiendo este concepto en un sentido amplio-, la cual convive con la convicción de que hay que defenderse de la sociedad existente más allá de este ámbito reducido de confianza. Así, esta experiencia del desapego dificultaría, a su vez, el desarrollo del conjunto de normas de reciprocidad y de actitudes colaborativas que según la literatura del capital social llevaría a los individuos participar activamente de sus comunidades y a confiar en sus instituciones [@uslanerDemocracySocialCapital1999; @zmerliSocialTrustAttitudes2008].
 