# Conclusiones

A lo largo de esta investigación se buscó analizar la influencia que la percepción del desempeño institucional y la confianza generalizada tienen sobre la confianza política de los ciudadanos chilenos. Lo anterior consistió en estudiar, por un lado, la relación directa que cada uno de estos factores manifiesta con el fenómeno de estudio y, por otro lado, la capacidad de la confianza generalizada para moderar la relación entre percepción del desempeño y confianza en las instituciones políticas. A su vez, se llevó a cabo una comparación de la magnitud del efecto que cada una de estas perspectivas tiene sobre la variable dependiente. Para esto, se construyeron una serie de modelos de regresión lineal múltiple (MCO) sobre datos secundarios extraídos de la Encuesta Latinobarómetro (*n* = 944), en su versión para el 2024. En primer lugar, los resultados del modelo evidencian que, en concordancia con las hipótesis planteadas (*H1*, *H2*, *H3*, *H4*), tanto la percepción del desempeño institucional -situación económica, reducción de la corrupción y justicia distributiva- como la confianza generalizada se relacionan positivamente con la confianza política. En segundo lugar, los análisis indican que la confianza generalizada modera positivamente la influencia que la percepción de la situación económica y de la desigualdad tienen sobre la confianza en este tipo de instituciones, pero no interactúa con la percepción de corrupción. Lo anterior dista de las hipótesis de moderación planteadas debido a que, aun cuando se encuentra este efecto moderador sobre dos de las variables de desempeño, el mismo se expresa en un sentido distinto al planteado en un principio (*H5*, *H6*, *H7*). Por último, se encontró que la confianza generalizada presenta un efecto sobre la confianza política mayor que la percepción de la situación económica y de la corrupción, pero menor que el que manifiesta la percepción de justicia distributiva, por lo que no se puede aceptar la última hipótesis planteada (*H8*).

Los resultados encontrados para el caso chileno contribuyen a la profundización del entendimiento sobre los factores asociados a la confianza política. En particular, se brinda evidencia que obliga a ir más allá de la dicotomía entre confianza estratégica y confianza generalizada, subyacente al debate en torno a la pertinencia de las perspectivas institucionales y socioculturales. Posicionándose en contra de aquellos que argumentan que la confianza generalizada tendría solo un efecto marginal sobre la confianza política, se argumenta que en ciertos tipos de sociedades de baja confianza este factor puede ser igual o más influyente que algunos asociados a la percepción del desempeño. Debido a lo anterior, se afirma la necesidad de avanzar hacia una comprensión de la confianza política como un fenómeno complejo, el cual tendría su origen en la interacción entre, por una parte, la percepción de un desempeño positivo de las instituciones en determinados ámbitos -confianza estratégica- y, por la otra, la presencia de una disposición a confiar en las personas más allá del circulo familiar -confianza generalizada-. Para avanzar en esta linea, se adoptó una concepción de la confianza generalizada como un lente a partir del cual los individuos que confían en los demás interpretan el mundo [@uslanerMoralFoundationsTrust2002]. La pertinencia de esta aproximación se manifiesta en el hallazgo de que la confianza en los demás potencia el efecto que la percepción de la economía y de la justicia distributiva tienen sobre la confianza política. Como posible explicación a este efecto potenciador, se plantea la posibilidad de que los individuos que confían en los demás interpreten los buenos desempeños en estos ámbitos como avances hacia el logro de un ideal igualitario, llevándolos a percibir a las instituciones como alineadas con sus valores y por tanto confiando más en ellas. Aunque esta explicación no resulte del todo satisfactoria, en cuanto no logra explicar la ausencia de este efecto para la percepción de la corrupción, permite estimular el debate a modo que las siguientes investigaciones pongan a prueba la capacidad moderadora de la confianza generalizada en esta relación.

A su vez, el análisis expuesto aporta a llenar el vacío de investigaciones empíricas que estudien la confianza política en Chile tomando en cuenta ambos tipos de factores. Mediante esta empresa, se demostró la pertinencia de este enfoque para la comprensión de la persistente caída en la confianza que suscitan las instituciones del país. En primera instancia, los resultados aquí presentados demuestran la necesidad de expandir la concepción de la percepción del desempeño institucional, incluyendo indicadores sobre corrupción y justicia distributiva. Lo anterior en cuanto ambos exhibieron una mayor influencia en la confianza política que la percepción de la situación económica nacional, lo cual se presenta como una particularidad del caso chileno. Para explicar estos resultados, se aludió al surgimiento de dos procesos que se han profundizado durante la última década en este país. El primero concierne a la aparición cada vez más frecuente en los últimos años de diversos casos de corrupción de alta importancia mediática que, aún cuando no han significado una baja sustantiva en los indicadores internacionales de corrupción política, han contribuido a la percepción de que las instituciones políticas chilenas y las élites que las ocupan abusan de su situación de poder para satisfacer sus intereses individuales, yendo en contra de los intereses comunes [@araujoDesmesurasDesencantosIrritaciones2019; @araujoCircuitoDesapegoNeoliberalismo2025a; @lunaDemocraciaMuertaChile2024]. El segundo, de más largo aliento, refiere a la introducción en el debate público de demandas distributivas en el marco de un proceso de politización de las desigualdades, las cuales tomarían como fundamento de sus exigencias la experiencia de una desigualdad cotidiana que se experimenta no solo en en la diferencia de ingresos, sino que también en la diferencia de acceso a servicios básicos y en las diferencias en el trato recibido [@castiglioniChallengesPoliticalRepresentation2016; @robertsRePoliticizingInequalitiesMovements2016; @sommaNoWaterOasis2021a]. Al igual que en el primero, en este las instituciones políticas también se ven como grandes responsables del malestar, en cuanto contribuirían a perpetuar un sistema que reproduce dichas desigualdades. En este sentido, frente a la reconocida paradoja entre el desempeño positivo de las instituciones chilenas y la extendida animadversión que generan en la ciudadanía, se plantea la necesidad de poner más atención en la distancia entre lo que expresan los indicadores y la experiencia cotidiana de los chilenos. A su vez, se exhibe que para estudiar esta paradoja resulta ineludible tener en consideración la importancia que los ciudadanos le dan a la corrupción y la desigualdad en la construcción de sus juicios de confianza.

En segundo instancia, esta investigación contribuye al estudio de este fenómeno en Chile al demostrar la importancia que tiene la confianza generalizada en la construcción de los juicios de confianza en las instituciones políticas. En particular, da cuenta de que por sí sola tendría un efecto mayor que dos de los tres indicadores de percepción del desempeño seleccionados. Para explicar esta situación, única en la literatura sobre apoyo político, se hace referencia al retraimiento hacia los círculos mas íntimos que estaría presenciando la ciudadanía chilena desde principios de siglo, y que tendría como correlato los bajos niveles de confianza generalizada [@cousinoSociabilidadAsociatividadEnsayo2000; @livertDeterminantesConfianzaSocial2024]. A su vez, se argumenta que el bajo nivel de confianza en los otros es solamente uno de los indicadores de un fenómeno de mayor alcance como lo es la erosión progresiva que ha sufrido el lazo social que une a los ciudadanos chilenos. Esta erosión tendría como consecuencia la expansión en la ciudadanía del desapego, estado en el cual los sujetos se distanciarían de las normas e instituciones que orientan la vida social, adoptando una actitud de defensa frente a los grupos que existen más allá de su limitado radio de confianza [@araujoDesmesurasDesencantosIrritaciones2019; @araujoCircuitoDesapegoNeoliberalismo2025a]. Lo anterior implicaría que los ciudadanos chilenos no posean el conjunto de orientaciones, actitudes y normas necesarias para desarrollar una cultura que promueva redes de cooperación y participación activa en la comunidad, la cual resulta imprescindible para generar confianza en las instituciones políticas. De esta forma, se afirma que es indeseable estudiar los factores asociados a la confianza política en Chile sin tener en cuenta este proceso. A su vez, como se puede evidenciar en los efectos de moderación, se plantea que la clave para entender la baja confianza de las instituciones chilenas se encuentra en la interacción entre el debilitamiento del lazo social y la percepción de las instituciones como abusivas y reproductoras de injusticias. 

El presente estudio cuenta con algunas limitaciones que se espera sean corregidas en posteriores investigaciones. La primera remite a que se construye sobre transversales. Lo anterior significa que los resultados presentados consisten en una foto sobre el estado de la cuestión en un momento determinado. En este sentido, está fuera de las posibilidades de este estudio el hacer conclusiones estadísticamente válidas sobre cómo cambia la intensidad de las relaciones encontradas a lo largo del tiempo. Así, aunque desde el punto de vista analítico se pueda argumentar que lo encontrado es parte de un proceso de larga data, desde lo puramente estadístico resulta necesario poner a prueba esta hipótesis usando modelos más avanzados -por ejemplo, modelos multinivel o modelos de ecuaciones estructurales- que permitan dar cuenta de las diferencias que estas relaciones exhiben en el tiempo. Relacionado con lo anterior, las limitaciones propias de los modelos de regresión lineal impiden incluir en el análisis variables contextuales que permitan comparar su influencia en la confianza política con la que tienen las variables de percepción. En este sentido, no podemos saber hasta qué punto, por ejemplo, el estado general de la desigualdad incide más o menos en el fenómeno de interés que la percepción de justicia distributiva. Por último, el carácter exploratorio de esta investigación llevó a que se decidiera por no expandir el radio de estudio hacia más países. Lo anterior resulta una limitancia en cuanto una investigación como esta se beneficiaría de la posibilidad de comparar los efectos encontrados con los que se exhiben en otros países de la región, a modo de saber si es que habría alguna tendencia (o divergencia) regional al respecto. Teniendo todo esto en consideración, para que los resultados de esta investigación sean concluyentes, se plantea la necesidad de que próximos estudios aborden la tarea de expandir su alcance en todos los ámbitos recién comentados.

